# Link the C runtime statically so the executable runs on machines that do not
# have the Visual C++ redistributable installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
